name: build-icons-vue-demo

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
      - run: |
          eval "$(ssh-agent)" && \
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}" && \
          ssh -o StrictHostKeyChecking=accept-new ${{ secrets.USER }}@${{ secrets.HOST }} rm -rf ${{ secrets.PATH }} && \
          scp -r dist/ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.PATH }}
